[profile.default]
optimizer = true
optimizer_runs = 10000
# via_ir = true # temporarily disable for faster snapshot

gas_reports = [
  # "*",
  "Grappa", 
  "OptionToken",
  "ChainlinkPricer"
]

[profile.lite]
via_ir = false
optimizer_runs = 200