[profile.default]
optimizer = true
optimizer_runs = 100000
# via_ir = true # temporarily disable for faster snapshot

gas_reports = [
  # "*",
  "Grappa", 
  "OptionToken",
  "FullMarginEngine",
  "FullMarginEngineV2",
  "ChainlinkOracle"
]

[profile.lite]
via_ir = false
optimizer_runs = 200