name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run forge fmt
        run: forge fmt --check
      - name: Check snapshot
        run: forge snapshot --check
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run tests
        run: forge test --gas-report

      - name: Run Coverage
        run: forge coverage --report lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: .
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./lcov.info
          name: grappa-coverage
          verbose: true